### ISSUE TITLE
Numix icons missing on Ubuntu 16.04 with icon themes "Numix" and "Numix-light"

### ISSUE THREAD

**Issue by JanSurft** [numixproject/numix-icon-theme#1073] opened 2016-05-16 11:46 UTC
I have a relatively fresh install of Ubuntu 16.04. In the Unity Tweak Tool, changing the theme to "Numix" or "Numix Daily" is working perfectly fine. Everything seems to change according to that theme.

Then I also want to change the Icon appearance to "Numix". This yields into some icons just missing. Some of them are: `System Settings->Appearance`, `System Settings->Language Support`, `System Settings->Text Entry`, `gnome-screenshot`, the default terminal icon and the default `help` icon. But there are more...

Numix-circle and Numix-circle-light are working just fine by the way, without any missing icons.

![icons-missing](https://cloud.githubusercontent.com/assets/10834314/15281386/e64032b4-1b3a-11e6-87f4-09d9d6225fb6.png)

**Comment by bil-elmoussaoui** [comment] 2016-05-16 11:47
It's normal, Numix (Base icon theme) does not provide any application icon!

**Comment by JanSurft** [comment] 2016-05-16 11:51
It should fall back on the default then shouldn't it, instead of showing nothing at all (and question-mark-placeholders on the Launcher)? At least it did that way on my Ubuntu 14.04 installation, as well it works like this on my Lubuntu 14.04 Laptop.

**Comment by bil-elmoussaoui** [comment] 2016-05-16 11:54
Well, those icons are missing from `hicolor`theme i guess. As the Numix base theme fall back to it and to `gnome` theme. We can't add a specific theme as a fallback for each distro out there..

**Comment by JanSurft** [comment] 2016-05-16 12:00
Well, nonetheless it is not working as it should. How does one fix that? It would be easier to be fixed by one who is familiar with the whole setup for icon themes.

**Comment by palob** [comment] 2016-05-16 12:08
Go to the Numix theme folder, open the ``index.theme`` file in a text editor and add ``humanity`` to the inheritance line such that it reads ``Inherits=humanity,gnome,hicolor``.

Or just install https://github.com/numixproject/numix-icon-theme-circle.

**Comment by wa4557** [comment] 2016-05-16 12:08
You can add `Inherits=Humanity` to the `index.theme` file in `usr/share/icons/Numix`

**Comment by palob** [comment] 2016-05-16 12:08
Is it ``humanity`` or ``Humanity``?

**Comment by bil-elmoussaoui** [comment] 2016-05-16 12:09
@palob I guess it's `Humanity`

**Comment by JanSurft** [comment] 2016-05-16 12:14
Thank you very much! `Inherits=Humanity,gnome,hicolor` is working. I have got all the icons back.

**Comment by palob** [comment] 2016-06-01 23:04
@JanSurft Is this fixed then?

**Comment by JanSurft** [comment] 2016-06-02 07:13
Kind of. I'm still a bit confused though. A friend of mine installed Ubuntu 16.04 and the numix icon theme, and he has no such problems. He even gets different icons for those that I was missing. (different from the ones in Humanity that I can see now)

**Comment by palob** [comment] 2016-06-02 08:21
How exactly did you install the theme and which parts of the "Numix suite"?
Do you want to have the [Numix Circle](https://github.com/numixproject/numix-icon-theme-circle) application icons show up?

**Comment by dirtydancing** [comment] 2016-07-09 12:42
Just for your information: This is a duplicate of https://github.com/numixproject/numix-icon-theme/issues/442, cf. also the conversation in https://github.com/numixproject/numix-icon-theme/pull/537.

**Closed** 2016-08-04 18:28 UTC
Labels: duplicate
