### ISSUE TITLE
Bluetooth indicator icon is missing

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme#1215] opened 2017-05-09 22:53 UTC
On fresh Ubuntu 17.04 install.
![screenshot from 2017-05-09 19-52-57](https://cloud.githubusercontent.com/assets/1277920/25876043/30f4aa62-34f1-11e7-8bc4-4ac45794039b.png)

**Comment by palob** [comment] 2017-05-10 09:16
That's probably Numix Circle icon ``bluetooth-active`` or ``blueman-active`` showing up where it shouldn't. At first sight the icon names don't sound too much like genuine app icon names.

Does anybody know if it's prudent to remove the icons from Circle? By the way, I can't reproduce this with GNOME.

@leoheck Is this with just Bluetooth turned on or is this any specific app?

**Comment by leoheck** [comment] 2017-05-11 21:59
@palob after one or 2 reboots, the icon got fine. Can we close this issue?

**Comment by Foggalong** [comment] 2017-05-17 20:39
That's super weird. Possibly an old version of the bluetooth indicator which had a bug in it?

**Comment by Foggalong** [comment] 2017-11-01 21:46
Gonna close this as unreproducable. I've not been able to get it, even with fresh installs of 17.04 so I'm assuming it's something that's since been patched? Weird

**Closed by Foggalong** 2017-11-01 21:46 UTC
Labels: bug
