### ISSUE TITLE
Numix cursor theme

### ISSUE THREAD

**Issue by wa4557** [numixproject/numix-icon-theme#949] opened 2015-12-13 15:13 UTC
I've started working on a Numix cursor theme (not finished yet) but some icons are already in a good shape (the first 6 for example, the rest is not from me yet). https://github.com/wa4557/numix-cursor-theme/tree/master/build/dark/x2

If this is finished this is something that could be added to the base theme, since a cursor-theme is the one thing that's still missing for a perfect numix-desktop. You think this is something?

**Comment by bil-elmoussaoui** [comment] 2015-12-13 15:18
Yes!! Nice design btw, and i really want to change the cursor theme to something more Numixy. :dancer:

**Comment by bil-elmoussaoui** [comment] 2015-12-13 18:30
What about having two versions? A light & dark one?

**Comment by wa4557** [comment] 2015-12-13 18:43
Sure. But first I have to complete all the icons..

**Comment by hlechner** [comment] 2015-12-13 19:22
Pretty nice! I loved it because it is based on my favorite cursor until now (Breeze) and it's more numix styled. :+1: 

Just an idea: if could change the color a little bit, just for use the same ton of blue, same ton of red, etc, on all cursors? I'm not sure about but I think it could be nice.

**Comment by wa4557** [comment] 2015-12-13 19:24
The icons that are from still from breeze,  I will change, though. The thing is not finisehd yet

**Comment by Foggalong** [comment] 2015-12-13 21:05
I'll chat more about this later, but just as a point of information: [someone tried doing one a while ago](https://github.com/uloco/numix-cursor)

**Comment by wa4557** [comment] 2015-12-13 21:16
I know, didn't like them though

**Comment by wa4557** [comment] 2015-12-16 20:09
Finished. Feedback?
![cursor](https://cloud.githubusercontent.com/assets/6475757/11852614/428edf1c-a439-11e5-8e40-60a6db90586e.png)

**Comment by hlechner** [comment] 2015-12-16 22:28
nice work specially on crosshair and pirate.

have you tested your cursors? I see that you've removed the "borders" from the symbols that are used on breeze ones, it seems more Numix however how it will interact with the all different background colors? I mean if the background is the same color with the symbol it will be hard to recognize I think

**Comment by wa4557** [comment] 2015-12-16 22:33
I'm using them right now and it looks good :) I did not remove the borders I just changed the borders from white to `#353535` so if the icon colour is the same as some colour in Numix it is still recognizable. I tried to use existing Numix design where possible

**Comment by hlechner** [comment] 2015-12-16 23:15
and how does the dnd-no-drop looks by removing the cursor's part behind of the symbol?

**Comment by wa4557** [comment] 2015-12-16 23:45
I've added a light theme, basically with inverted colours

**Comment by wa4557** [comment] 2015-12-16 23:49
@hlechner Was considering this, but I'm not so sure about that
![unbenannt](https://cloud.githubusercontent.com/assets/6475757/11857378/f4f6fc02-a457-11e5-80de-c3ed0640bed9.png)

**Comment by hlechner** [comment] 2015-12-16 23:50
I personally liked :+1:  , I think it's better than before

**Comment by wa4557** [comment] 2015-12-16 23:56
Yeah looks better. I changed it :+1:

**Comment by hlechner** [comment] 2015-12-17 00:33
If in case this cursor can't be published into numix icon theme, please do it in your own and comment like *based on numix theme icon* (with the name that you want to) and share in gnome-look.

Because it'll be enjoyed by the community

**Comment by Foggalong** [comment] 2015-12-17 10:25
I'll be honest, I was a bit sceptical about this. Various people have tried in the past and it's fell flat, but I do like where this is going :) I've on my last few days of Uni term so a bit busy right now but I'll write more detailed thoughts asap

**Comment by wa4557** [comment] 2015-12-17 15:13
I've included installation instructions in the README. So if anyone want's to test it and report missing cursor icons, please go ahead :)

**Comment by bil-elmoussaoui** [comment] 2015-12-17 15:22
@wa4557 If you can change the folder name from Numix/Numix-Light to Numix-Cursor/Numix-Light-Cursor or something else ;) And there's an issue with Google Chrome not using the default cursors (not only Numix ones) Do you think there's a work around to fix it ?

**Comment by wa4557** [comment] 2015-12-17 15:35
No because that's intentional. The idea is, that you have the cursors alongside with your icon installation.  Therefore the name has to be the same... For me Chrome uses the Numix cursors :)

**Comment by bil-elmoussaoui** [comment] 2015-12-17 15:41
I see, thanks! I will try the beta version of Chrome and see if this will change;

**Comment by palob** [comment] 2015-12-17 17:30
Hmm, I think part of the Numix identity is that the icons usually come without any sort of outline.
As a matter of course due to contrast reasons that's unfavourable for cursors.

Is it possible to make use of the alpha channel and have a transparent shadow?
Maybe it's possible to get a no-outline design up this way.

**Comment by wa4557** [comment] 2015-12-17 17:37
I don't think cursors work without an outline simply given the fact that there will always be white and black  (or dark) areas on your screen. Cursor icons without an outline would be pretty much useless (or I assign a completely dfiferent colour like to the icons, which is als a bad idea imo). All the cursor themes I have seen so far, do have an outline (even the flattest ones). I don't see how a transparent shadow could do the same trick, but I'm happy to try it out...

**Comment by Foggalong** [comment] 2015-12-17 19:45
Yeah cursors absolutely need an outline. It's the same reason image macros use the style they do.
![meme](http://d22zlbw5ff7yk5.cloudfront.net/images/stash-1-507c8da7ae6f2.png)

**Comment by hlechner** [comment] 2015-12-18 17:04
@wa4557 have you tried the color ``#4d4d4d`` in the inverted one? It's the default color of breeze cursor, that color still dark but not too black.

**Comment by wa4557** [comment] 2015-12-18 17:10
Is the current one too dark? I'd like to have numix colours not breeze
colours....

Henrique Lechner <notifications@github.com> schrieb am Fr., 18. Dez. 2015
18:04:

**Comment by hlechner** [comment] 2015-12-18 17:14
It's just a personal preference actually, I'm used to the dark cursors not too black.

Oh, I didn't notice that the black is a Numix color, then it make total sense :+1:

**Comment by wa4557** [comment] 2016-01-10 09:45
@Foggalong Any thoughts on this? I've been using it for quite some time now and really like it :)

**Comment by bil-elmoussaoui** [comment] 2016-01-10 09:53
I'm using it too :+1:

**Comment by Foggalong** [comment] 2016-01-11 19:40
I'm thinking I'd like to see this yeah :) The one thing I'm not to keen on is it been automatically applied with the icon theme. Numix is built around a modular themeing system rather than all being included as one and I don't think the cursor should be an exception to that.

@bil-elmoussaoui did your issues with Chrome get sorted?

**Comment by bil-elmoussaoui** [comment] 2016-01-11 19:43
Yes! :+1: 
![screenshot from 2016-01-11 20-41-58](https://cloud.githubusercontent.com/assets/7660997/12244445/e60dedd0-b8a3-11e5-9bec-d2ffd5facfad.png)

**Comment by nfnty** [comment] 2016-01-15 07:07
Looks great! Would be nice with more sizes.

**Comment by wa4557** [comment] 2016-01-15 12:36
@Foggalong It is NOT automatically applied if the folder is included in the theme. The user still has to select it using `unity-tweak-tool` etc... The icons are just sitting there doing nothing if the user does not actively want to use them...
Btw: I'd gladly transfer the repo to numixproject if you want...

@nfnty Why more sizes? There is one bigger size for HIDPI and beamers etc. and one for normal desktops. For what would you need more sizes?

**Comment by Foggalong** [comment] 2016-01-15 12:47
@wa4557 ahhh, okay. That's sounds aokay to me :+1:

**Comment by wa4557** [comment] 2016-01-15 12:53
So a PR then? Should I transfer the repo as well, or do you want me to keep it?

**Comment by nfnty** [comment] 2016-01-15 13:39
@wa4557 The smallest size is too big. Need 16 and 20.

**Comment by wa4557** [comment] 2016-01-15 14:23
I probably could do that, but where do you need smaller cursors? All the cursor themes I have seen so far only do have the same sizes...

**Comment by nfnty** [comment] 2016-01-15 14:34
It's a personal preference; I want the cursor to be as small as possible. Same with all small/slim cursor themes. Added benefit is that you can scale them to 32 and 40.

**Comment by nfnty** [comment] 2016-02-03 00:23
@wa4557 Any updates?

**Comment by wa4557** [comment] 2016-02-03 13:01
I'll try to do this asap. Unfortunately I'm pretty occupied these days, and I cannot contribute as much as I once did :(

**Comment by nfnty** [comment] 2016-02-03 14:39
No problem. Tell me if you need any help.

**Comment by uloco** [comment] 2016-07-11 05:50
Why doesn't anyone consider this one here?
I wrote an email to all of the numix project team members when I was creating this cursor but nobody wrote back. You don't like the design, or what is it?
 https://github.com/uloco/numix-cursor

It's also on gnome-look
https://www.gnome-look.org/p/999876/

**Comment by Foggalong** [comment] 2016-07-12 11:00
@uloco Sorry about that, we had a lot of admin problems over the last year which meant some emails regarding external projects went unanswered. The reasons for going with yours were related to design. While I personally prefer your basic cursor shape to @wa4557's quite a few of the symbols used aren't consistent with those used in the Numix icon theme. I'm really sorry this wasn't communicated to you though because it could have possibly prevented duplication of effort and got more people involved in the project :(

**Comment by uloco** [comment] 2016-07-12 11:38
Cool, thanks for answering this time :) 
How about merging the projects? I like your icons, too! It really took a quite effort to get all xcursor alias links right. I also optimized the position of the cursor for preventing flickering when switching between links and text etc. 
Your cursor just looks like another extended  clone of many cursors on gnome-look.org....

**Comment by uloco** [comment] 2016-07-12 11:41
Install it and use it, so you can test how it feels with your theme. I am using it for a long time now and it's great ;)

**Comment by palob** [comment] 2016-07-12 15:55
@uloco I think a problem with your theme is that pretty much every cursor lacks proper alignment to the pixel grid as a result of which the theme looks blurry.

This issue however is also present with the hands icons of @wa4557's theme.
![misalignment2](https://cloud.githubusercontent.com/assets/7050624/16773849/c5d53c3a-4859-11e6-9960-669944a90ef8.png)

@wa4557 Is there anything you can do about it?

**Comment by uloco** [comment] 2016-07-12 17:06
I don't think the blurriness has anything to do with the grid. It's more the conversion from svg to png I think, causing quality loss. Why should the grid make it look blurry? The cursors are off the grid on purpose, so there will be no flickering when hovering a link and text. I tried the cursors with proper alignment and it didn't show sharper.

**Comment by palob** [comment] 2016-07-12 18:22
The grid is the representation for the pixels on your screen. If there's two different colours in one grid box of your SVG the respective pixel's color will be interpolated.
Take for example a black square which isn't aligned with the grid on a white background. On your screen a grey line will then be dislayed around the the black area.

**Comment by uloco** [comment] 2016-07-12 19:11
Hey, this sounds really evident. Didn't knew that the interpolation is happening because of this. I did not adjust inkscape to do so, you're right :)
We could fix this, it's just positioning ;)
By flickering I mean the following:
In theory it isn't important where your cursors pointing x and y coordinate are, because you can adjust this with the xcursorgen command. The problem is, when you got a normal pointer pointing to say (x,y)=(5,5) and you have a hand pointing to (x,y)=(10,10) you will see a little flicker when hovering a link. On a lot of custom cursors this happens and it is annoying. (at least on ubuntu...)

**Comment by wa4557** [comment] 2016-07-12 19:18
@uloco I actually like your cursors, just not all of them (I really like your main cursor icons, I'm not a big fan of your "hand" icons). At least I'd say that it is necessary that Numix icons are used where possible (like `not-allowed` in my screenshot for example). That being said I have absolutely no problem if some icons are changed / design changed, or your cursor theme is merged instead of mine. This is however not for me to decide :) that's why I proposed my icons here, that's why I opened this issue to ask if there's an interest for it.

I like my icons (using them right now) but I'm open to discuss changes.

@palob: Yeah no not really, it looks strange if only one line is aligned to grid (index finger). An exception for that would be the main cursor icons

**Comment by uloco** [comment] 2016-07-13 06:18
@wa4557 I am using your cursor right now and it does have the flickering problem like other cursors I mentioned above. Try hovering text, then a link and then nothing. Repeat this and you will see the cursor jumping around. This does not happen with mine, because I adjusted the positioning, just try it. Perhaps this is just an Ubuntu issue, but it is clearly annoying for me.

How should we proceed further? I think we should vote for the ones we like on your theme and mine. Then we will have to agree some core principles like outline thickness and colour etc., so we can adjust the theme accordingly.

@wa4557 could you provide a picture where all of your icons are visible, so we could mark the ones we like?

Here are mine:

![screenshot from 2016-07-13 08-14-52](https://cloud.githubusercontent.com/assets/8818340/16793524/f16ddfaa-48d1-11e6-9735-3e467943f5fe.png)

I could say, I really like the base icons of my theme:
The arrow, the watch, the pointing hand, the drag-and-drop and open hand. But I personally don't like the additional icons on these ones like the copy/move/not-allowed and how they are aligned. I do like how you arranged your drag-and-drop icons additions by cutting some of the pointer away. That would be a great start. And of course adding numix style icons whereever possible ;)

**Comment by palob** [comment] 2016-07-13 08:21
@wa4557 I noticed that the base line of your hand cursors is just blurry because the symbols are positioned at ``Y 5.5``. Couldn't you just move them up/down by 0.5 px?

**Comment by wa4557** [comment] 2016-07-13 08:50
@palob Oh, sure, that's something I missed

@uloco Here a screenshot. Concerning flickering: Yes you are right, the positioning is not perfect yet, but can be changed relatively easy.

![untitled](https://cloud.githubusercontent.com/assets/6475757/16797125/55307b38-48e6-11e6-8454-1823b65dd095.png)

I'm afraid we disagree on the choice of your favourite icons. I agree that your main arrow is very nice, I'm not so fond of your grabbing icons (or hand icons in general) though... I think it's clear that both of us like the icons we made, and since we are both not members of the Numix theme, I think they should decide, which icons of which theme should be taken. I don't like to do work twice. 

If a choice is made however, I'm of course willing to put work in it to change them accordingly. As @palob pointed out, however, your icons need some extra work since the aligning of the icons is an important thing to do...

**Comment by uloco** [comment] 2016-07-13 08:54
Yeah I agree on all points. Let the numix guys decide ;)

**Comment by nfnty** [comment] 2016-07-13 13:49
+1 for @wa4557 theme.

@uloco theme is way too colorful, jagged and has too thick lines. IMO a cursor theme should be very minimalistic and smooth.

**Comment by uloco** [comment] 2016-07-13 14:11
@nfnty Thanks for sharing your opinion. The color is the numix main colour, to match design guidelines. I planned on making this themeable like numix-folders. You can easily create ones without the primary colour. The thickness of the lines needs to be adjusted anyway to merge the themes, so please rate the motives, not the looks. :wink:

**Closed** 2017-11-01 21:35 UTC
Labels: enhancement, request
