### ISSUE TITLE
Missing Synaptic Package Manager action icons

### ISSUE THREAD

**Issue by Sadi58** [numixproject/numix-icon-theme#504] opened 2015-05-27 14:44 UTC
Numix icon theme includes some (6) but not all action icons for Synaptic Package Manager, i.e. the following 8 are missing:
```
package-available.svg
package-available-locked.svg
package-broken.svg
package-installed-locked.svg
package-installed-outdated.svg
package-installed-updated.svg
package-new.svg
package-supported.svg
```
I've attempted to create them using the same master image and already used emblems such as "new", "ok", "locked", "install", which are all here:
https://www.dropbox.com/s/nwtao68xkwegstp/numix-missing-synaptic-actions.zip?dl=0
I doubt this amateur work will be regarded acceptable for incorporating into the icon set though ;-)

**Comment by bil-elmoussaoui** [comment] 2015-05-27 15:20
those were already reported before here #184 . You can create pull request and the numix designers will decide if they are good to be merged

**Comment by Foggalong** [comment] 2015-05-27 15:23
@bil-elmoussaoui Is this a duplicate of #184 then?

**Comment by bil-elmoussaoui** [comment] 2015-05-27 15:24
Yeah; you can close this

**Comment by Foggalong** [comment] 2015-05-27 15:25
Thanks!

**Closed** 2015-05-27 15:25 UTC
Labels: duplicate
