### ISSUE TITLE
Top bar icons

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme#779] opened 2015-10-14 14:17 UTC
Hi, the last update changed the bluetooth icon. This is right? Is it possible to make the white icon with no bacground icon back?

![topbar](https://cloud.githubusercontent.com/assets/1277920/10486368/04c1acc4-7265-11e5-8697-c28dcf188a6c.png)

**Comment by Foggalong** [comment] 2015-10-14 14:34
Duplicate of numix-icon-theme-circle#2601

**Closed** 2015-10-14 14:34 UTC
Labels: duplicate

**Comment by keunes** [comment] 2015-10-16 08:51
Also see discussion at https://github.com/numixproject/numix-icon-theme-circle/issues/2274
