### ISSUE TITLE
Missing "default mail reader" icon

### ISSUE THREAD

**Issue by Kzer-Za** [numixproject/numix-icon-theme#1223] opened 2017-06-01 14:24 UTC
Numix seems to lack an icon for default mail application. You know, not for a specific app, but for an app set as the default mail reader. I'm going to attach two screenshots from a menu that shows several apps, including default web-browser and default mail reader. One is with Vertex-Maia icon theme applied and the other one with Numix. As you can see, mail reader icon is missing.

![2017-06-01_17-14-05](https://cloud.githubusercontent.com/assets/26425206/26684203/fe811da8-46ee-11e7-929a-d5ba6dab1b82.png)
![2017-06-01_17-14-33](https://cloud.githubusercontent.com/assets/26425206/26684202/fe7c8270-46ee-11e7-9ca5-4e70bff3f1c8.png)

**Comment by palob** [comment] 2017-06-02 21:18
I don't see any issue here. Numix base isn't supposed to provide any app icons.
Our app icon theme is Numix Circle https://github.com/numixproject/numix-icon-theme-circle which you need to install for app icon theming.

As far as I can see Vertex-Maia is a theme based on an outdated version of our Numix Circle icons mixed with base icons from elsewhere.

**Comment by Kzer-Za** [comment] 2017-06-03 09:51
Well, what I'm talking about is not an actual app, it's an abstraction - a default mail reader, just as there is a default web browser or default file manager. As you can see in the pics above, this menu shows exactly these icons - not for specific apps, but for abstractions (I use Thunar for FM and Firefox for browser, but in the pics you can see these are not Thunar and Firefox icons).

And it makes sense that the icons for these abstractions should be not in a theme that provides app icons but in a theme for basic icons, because not everyone would want to install an app icon theme. I, for example, prefer to see the native app icons (the icons that application developers chose for their apps). So it seems to me that a basic theme should contain icons for these abstractions (default web browser, FM, mail reader). If you think otherwise, then it seems logical to also remove icons for default FM and default browser from Numix theme.

**Comment by wa4557** [comment] 2017-06-03 09:54
You can open `index.theme` in `/usr/share/icons/Numix` (or wherever your theme is installed, and change this line

`Inherits=gnome,hicolor`

to 

`Inherits=gnome,hicolor, Humanity`

that should fix it.

**Comment by palob** [comment] 2017-06-03 09:56
I think he is on Manjaro where there is no Humanity preinstalled.

**Comment by wa4557** [comment] 2017-06-03 09:57
Than you should add the default theme of whichever distro you are using

**Comment by Kzer-Za** [comment] 2017-06-03 10:07
I added the default theme in the file indicated above, that fixed it for me. Thanks! Still, any new user switching to Numix theme would have the same issue.

**Comment by wa4557** [comment] 2017-06-03 10:10
@Kzer-Za Yes we are aware of that. The issue is that the theme should be distro-agnostic which makes it hard to figure out which themes to put in that file in which order

**Comment by palob** [comment] 2017-06-03 10:13
What was the issue again with just stuffing every possible theme in there?

**Comment by wa4557** [comment] 2017-06-03 10:14
Maybe there wasn't an issue? I'd just do that, definitely better than the status quo. One issue might be the order of the inherited themes

**Comment by palob** [comment] 2017-06-03 10:16
We definitely need breeze for KDE compatibility.

**Comment by wa4557** [comment] 2017-06-03 10:18
Humanity as well for gnome. elementary maybe?

**Comment by bil-elmoussaoui** [comment] 2017-06-03 10:26
@wa4557 Gnome uses Adwaita instead of  Humanity :)

**Comment by palob** [comment] 2017-06-03 10:27
Humanity could even be discontinued after Ubuntu 17.10.

**Comment by wa4557** [comment] 2017-06-03 10:30
Right, well then a good start would be Adwaita and breeze I guess

**Comment by Kzer-Za** [comment] 2017-06-03 10:30
For Manjaro it's Vertex-Maia. I wish there was an environment variable where distros would put their default theme.

**Comment by Foggalong** [comment] 2017-06-15 18:52
Wasn't there some issue where things would crash if a theme was set in the inherits but not actually installed by the theme?

**Comment by palob** [comment] 2023-02-15 22:38
Closing because ``numix-icon-theme`` is made to be used with one of our app icon themes.

**Closed by palob** 2023-02-15 22:38 UTC
