### ISSUE TITLE
Some icons now appear pixelated on Gnome 3.14

### ISSUE THREAD

**Issue by spacepluk** [numixproject/numix-icon-theme#192] opened 2014-10-10 06:09 UTC
Like this:

![screenshot from 2014-10-10 08 52 03](https://cloud.githubusercontent.com/assets/824762/4588480/f6aa3bb8-5043-11e4-85f6-ae4b458e836a.png)

**Comment by spacepluk** [comment] 2015-03-31 21:40
This bug is back on 3.16.

**Comment by wa4557** [comment] 2015-03-31 21:44
Try the version from github instead of the one from PPA. Should be fixed because all the status icons moved to numix-base

**Comment by spacepluk** [comment] 2015-03-31 22:33
I'm using AUR's package in Arch Linux which takes the latest version from github.

**Comment by Foggalong** [comment] 2015-04-01 01:44
The icons being in Numix base is exactly the problem here. Because base theme doesn't have any appnicons is going the same named panel icons and using them for everything. Ideal would be to take

**Comment by wa4557** [comment] 2015-04-01 06:54
Or merge base and circle or add an inbetween numix-mono as @dirtydancing suggested :)

**Comment by dirtydancing** [comment] 2015-04-01 07:27
@wa4557 Please cf. here https://github.com/numixproject/numix-icon-theme/issues/107#issuecomment-60065491 for the difficulties that an additional numix-mono would entail :-)

Merging base and circle leads to the problem (in this context) that e.g. for those apps that do not have a distinct app status icon name (e.g. Google Chrome and VLC), those "status icons" would have to be deleted, whereas they should not be picked up from Numix base because Numix-Circle inherits from Numix base and so always the Circle app icon from Numix-Circle should be picked up, without recourse to Numix base.

(Of course, merging base and circle e.g. would also mean that also Square and base would have to be merged, and non-uniformity and base, so all the modularity with the different Numix icon themes would get lost. But that is a more general point.)

Then again, this thread seems to suggest that the app "status icons" for Google Chrome and for VLC are still picked up with gtk 3.16, even though they are in base? That would need further inquiry.

@spacepluk Could you provide a current screenshot, if possible? We need to assemble evidence here and possibly try and reproduce this :-)

Currently, I believe that the symlink approach suggested in https://github.com/numixproject/numix-icon-theme/issues/190 ist the most promising (if that is possible at all). Probably this conversation should be continued over at https://github.com/numixproject/numix-icon-theme/issues/190 anyways.

**Comment by spacepluk** [comment] 2015-04-01 08:00
Sure :) there you go:
![rorb4iv](https://cloud.githubusercontent.com/assets/824762/6936766/356c4c90-d85e-11e4-8d22-b018392d3351.png)

**Comment by spacepluk** [comment] 2015-04-01 08:09
I'm using Gnome 3.16 from Arch's testing repository and [this version](https://github.com/numixproject/numix-icon-theme/commit/afaab3b85a17f62a1a00d21ad82d0c8421a71214) of numix-icon-theme.  Let me know if you need more info.

**Comment by dirtydancing** [comment] 2015-04-01 08:37
@spacepluk Thanks! Ok, we need this screenshot with current (current via GitHub) Numix-**Circle** icon theme (which inherits from Numix base).

This screenshot is showing Numix base (numix-icon-theme), and this is expected behaviour.

Actually, apparently I got confused myself by this, because for some reason, I was thinking that this is about Numix-Circle, whereas your screenshot from above clearly shows Numix-base :-) Sorry for that.

But could you still provide a screenshot with Numix-Circle, if possible? It seems like s.th. in the icon lookup has changed with gtk 3.16, and I would like to exclude the notion "one bug fixed, another bug added". So it would be good to know that currently, with Numix-**Circle**, the correct Circle app icons are still shown.

@wa4557 Indeed an additional numix-mono would solve this situation (only Numix base used, not Numix-Circle), because the app status icons would not be in base anymore, but in mono.

@Foggalong With the current inheritence structure, indeed just adding "-panel" to those icons that use the same name would solve this. They are not picked up anyways (at least until gtk 3.16, as far as we can tell at the moment).

**Comment by dirtydancing** [comment] 2015-04-01 09:26
@spacepluk To clarify: esp. the marked smaller icons on the left side would be of interest in this context for a corresponding screenshot with Numix-**Circle** (the larger ones in the app overview should show Circle app icons anyways):

![356c4c90-d85e-11e4-8d22-b018392d3351](https://cloud.githubusercontent.com/assets/7164227/6938131/4a07300e-d861-11e4-8f63-aa1294d256ed.png)

**Comment by spacepluk** [comment] 2015-04-01 11:56
@dirtydancing I see, now I need to get some work done, but I'll test again later with the proper config and post the screenshot :)

**Comment by spacepluk** [comment] 2015-04-01 13:46
Numix-Circle works as expected. I'd like to keep the stock app icons though, is that possible?

**Comment by dirtydancing** [comment] 2015-04-01 14:28
@spacepluk Thanks for helping out with your screenshot! This demonstrates that the Circle app icons are used also for smaller sizes (also with gtk 3.16), and that the "status icons" with identical names do not interfere.

To your question: I think it should be possible to just use Numix base and keep the stock app icons, without having to deal with these pixelated and blown up "status icons" causing breakage with the stock app icons.

@Foggalong Is there a reason NOT to rename these into `*-panel.svg`? It might make sense to make a (short?) list of those renamed, to keep track. As of now, those "status icons" that have an identical naming to the actual app icons are not picked up anyways, and they will cause breakage no matter what kind of icon theme inheritance structure there is.

So I would agree that it makes sense to just rename these into `*-panel.svg`.

(And to keep them renamed rather than delete them, so a user who might have a use for them can make use of them, and in case that the app developers change the app status icons name to a distinct name, the corresponding Numix app status icon will already be waiting.)

So far, I have seen:

- google-chrome.svg
- spotify-client.svg
- vlc.svg

@wa4557 Any thoughts on this from your side (just in case)?

**Comment by dirtydancing** [comment] 2015-04-01 14:47
Actually, for better identification of these renamed icons (and so an extra list would not even be needed), they might also just be renamed to e.g. `renamed-*.svg`.

**Comment by pgera** [comment] 2015-05-04 23:19
Since this is a regression in the base theme, is it possible to revert to the last known good state until a proper fix is created ?

**Comment by dirtydancing** [comment] 2015-05-05 07:19
@pgera Good question! As far as I can tell, reverting is not an option at this point.

Reverting entirely to the previous state would mean going back a long time. Not really an option imo. Still, going back in time to "freeze" Numix base in the PPA at the same point as currenty Numix-Circle in the PPA would preserve the previous state. But this would mean losing many changes in base since then, and it would probably break the Numix-Folders integration and probably other aspects as well.

And putting the "toxic" status icons that are named identical to their corresponding app icons back into Numix-Circle would cause the same regression in Numix-Circle, so that would not be an option either.

**Comment by dirtydancing** [comment] 2015-05-05 07:24
Ah, I might have overlooked that those "toxic" status icons actually still are in Numix-Circle in the PPA? Anyways, to avoid further complications I think that addressing this issue is preferable to any reverting.

**Comment by dirtydancing** [comment] 2015-05-05 07:41
Alas, I might have misunderstood the question entirely, as it might be related to the master branch on GitHub and not to the PPA, and it might refer to a specific commit. Happy to stand corrected here :)

**Comment by dirtydancing** [comment] 2015-06-06 11:45
@wa4557 Do we have a current list of the "toxic" app status icons that would have to be renamed?

@Foggalong I would suggest to go ahead and rename these "toxic" icons into `renamed-*.svg`.

Having run Arch/GNOME Shell for a while now, I can confirm that this is a rather annoying issue when using Numix base (even worse in Numix base than when they were located in Numix-Circle, because in Numix base these icons show up in every size).

imo, if the app developers care for a dedicated monochrome panel status icon, it is up to the app devs to properly name such icon distinct from the actual app icon. In this case, I do not see a way how Numix could cater to this. In contrast to e.g. the "Arch Avahi issue", cf. https://github.com/numixproject/numix-icon-theme-circle/issues/1963 and https://github.com/numixproject/numix-icon-theme/pull/468, this cannot be addressed along the way without causing other breakage.

At the same time, this would be a first preliminary step for tackling https://github.com/numixproject/numix-icon-theme/issues/190. At this point, there is no need yet to move these icons or to add any folder symlinks. The present "fix" is only about renaming.

And keeping these "toxic" status icons around as `renamed-*.svg` would allow users to re-rename them for their individual setting. E.g., re-renaming these icons might make sense for the top panel in Ubuntu/Unity when using Numix-**Circle**, again depending on the individual settings and preferences.

**Comment by wa4557** [comment] 2015-06-06 12:06
Here you go. For the icons with three question marks it is probably better to delete those icons from circle rather then base
```
audio-recorder.svg 
blueman-active.svg (?)
blueman-disabled.svg (?)
blueman.svg 
bluetooth-active.svg (?)
bluetooth.svg
brasero.svg
clipit-trayicon.svg (???) (not sure)
deluge.svg
evernote.svg
everpad.svg (can be deleted - unnecessary)
fluxgui.svg
gnome-mplayer.svg
google-chrome-beta.svg
google-chrome.svg
google-chrome-unstable.svg
hb-icon.svg
hexchat.svg
hipchat-attention.svg (???)
hipchat.svg
ibus-keyboard.svg (probably do not delete)
indicator-weather.svg
input-keyboard.svg
nitroshare.svg
nvidia.svg
pidgin.svg
psensor.svg
qbittorrent.svg
quiterss.svg
simplescreenrecorder.svg
spotify-client.svg
synapse.svg
vlc.svg
weather-clear.svg (???)
xfce4-notes-plugin.svg
xfce-system-lock.svg
xfpm-ac-adapter.svg
xnoise.svg
```

**Comment by wa4557** [comment] 2015-06-06 12:13
On a second thought, it would be even better to not rename them and add them to @Foggalong 's `hardode-fixer` script and change the icon line of the app-icon, and rename the icons in `circle/square`?

**Comment by dirtydancing** [comment] 2015-06-06 12:20
@wa4557 Thanks for providing the current list!

I am not sure what you mean by changing the icon line in the .desktop file. Is this referring to a special status icon line? The status icon names are not specifically listed in the .desktop file, or are they?

I would not recommend to rename into `*-panel.svg` because this will only cause more confusion, as several apps actually already use `*-panel.svg`. This would blur the distinction between "correct" status icon names and renamed "toxic" icon names.

As to using the hardcode-fixer script: I am not sure if that should be mandatory in order to fix this issue.

**Comment by bil-elmoussaoui** [comment] 2015-06-06 12:28
There's more applications like : autokey, gnome-pie..

**Comment by dirtydancing** [comment] 2015-06-06 12:29
In addition: is the hardcode-fixer script of any relevance for Numix base? This is a Numix base issue.

**Comment by dirtydancing** [comment] 2015-06-06 12:32
@bil-elmoussaoui E.g. gnome-pie is not affected by this, in Arch/GNOME Shell I get the correct icon (in the overview, there is a current issue about the "status" icon). gnome-pie apparently does not have a "toxic" status icon that is also named `gnome-pie`, just like the app icon itself.

**Comment by dirtydancing** [comment] 2015-06-06 12:35
To clarify: current gnome-pie tray icon issue with GNOME Shell 3.16: https://github.com/Simmesimme/Gnome-Pie/issues/107. As far as I can tell, this is not related to the issue discussed here.

**Comment by bil-elmoussaoui** [comment] 2015-06-06 12:42
@dirtydancing well it's , i'm using Numix with elementary Freya and those icons looks like that, when i do use the default theme of elementary the icons looks normal.
![capture du 2015-06-06 14 32 04](https://cloud.githubusercontent.com/assets/7660997/8019663/ee3f7510-0c59-11e5-9a5b-8b772d120f79.png)
And for Hardcode Tray, it's a script that fixes the hardcoded indicator icons like spotify... [https://github.com/bil-elmoussaoui/Hardcode-Tray](For more informations)

**Comment by dirtydancing** [comment] 2015-06-06 12:48
@bil-elmoussaoui You are referring to https://github.com/numixproject/numix-icon-theme/issues/190, are you not? These issues are very complex, I am only trying to get started somewhere.

This present issue (isolated and as a part of https://github.com/numixproject/numix-icon-theme/issues/190) is only concerned with pixelated monochrome (status) icons showing up as regular app icons when Numix base is used. Nothing to do with the tray at all.

**Comment by bil-elmoussaoui** [comment] 2015-06-06 12:51
My bad :P

**Comment by dirtydancing** [comment] 2015-06-06 12:51
No problem at all, glad you are joining in here :)

**Comment by wa4557** [comment] 2015-06-06 12:52
Yeah using a script to fix that is indeed problematic, thinking about this a bit more this would lead to more problems than solutions....
as for #190: The longer we wait to fix this one, the harder it will get (because more and more icons needs to be moved etc...)

**Comment by dirtydancing** [comment] 2015-06-06 13:13
@wa4557 Agreed. Alas, looking at your list of "toxic" app status icons, there are some icons on there that iirc are currently in discussion also for other reaons, e.g. bluetooth/blueman.

Why not just start with the obvious ones that have come up so far, and possibly take the renaming further according to further issue reports? The moving etc. for https://github.com/numixproject/numix-icon-theme/issues/190 can take place whether an icon has been renamed or not.

And in case other issues should be caused by this, the `renamed-*.svg` **status** icons are easy to spot.

For this present issue, I would suggest to go ahead with these **status** icons in `/16x16/status`, `/22x22/status` and `/24x24/status` in `Numix` as well as in `Numix-Light`:

```
brasero.svg -> renamed-brasero.svg
google-chrome-beta.svg -> renamed-google-chrome-beta.svg
google-chrome.svg -> renamed-google-chrome.svg
google-chrome-unstable.svg -> renamed-google-chrome-unstable.svg
spotify-client.svg -> renamed-spotify-client.svg
vlc.svg -> renamed-vlc.svg
```

**Comment by wa4557** [comment] 2015-06-06 13:17
If you add 
```
deluge 
everpad / evernote
pidgin ``` 
I think it's a good start

**Comment by dirtydancing** [comment] 2015-06-06 16:21
OK, created a PR with the above, cf. https://github.com/numixproject/numix-icon-theme/pull/533.

For this, I did not include deluge, as there were deluge-panel symlinks, so I figure this one would need to be tested, same for everpad/evernote, there is also everpad-mono, actually also pidgin with many icons, and there are also psensor symlinks.

I wanted to keep this as simple and straightforward as possible, so I included the icons that I listed before (brasero, 3x google-chrome, vlc, I did not include spotify-client either because there is also a symlink spotify-indicator pointing to it, so I guess also this one would need testing).

@Foggalong Please feel free to close the PR if you think that this is not the way to go. Nothing about this issue seems to be straightforward :)

**Comment by wa4557** [comment] 2015-07-08 10:40
Ok I think I figured out which icons need to be renamed. My suggestions:
```
blueman
bluetooth
brasero
clipit-trayicon
deluge
evernote
everpad
fluxgui
gnome-mplayer
google-chrome
google-chrome-beta
google-chrome-unstable
hb-icon
hexchat
hipchat
indicator-weather
nitroshare
nvidia
pidgin
psensor
qbittorrent
quiterss
simplescreenrecorder
spotify-client
synapse
vlc
xfce4-notes-plugin
xnoise
```

A manageable list imo

**Comment by dirtydancing** [comment] 2015-07-08 11:10
@wa4557 Great! Could you turn this into a to-do list, so we can put a checkmark to the renamed icons?

I figure this still leaves the problem with all the smylinks, cf. above? I can close my PR https://github.com/numixproject/numix-icon-theme/pull/533 from above if you would like to tackle this yourself in one PR. Otherwise, I would suggest to merge my PR from above to get this started (with Brasero, Google Chrome, VLC).

**Comment by wa4557** [comment] 2015-07-08 11:17
If symlinks I suggest to switch places. Turn the files that are symlinks to the toxic icons in real files, and the renamed icons to symlinks to the corresponding real file

**Comment by dirtydancing** [comment] 2015-07-08 11:26
Makes sense to me. We will just have to see how that works out for all icons/symlinks while going along.

As to `blueman` and `bluetooth` on your list: these are currently in discussion and would be fixed alongside https://github.com/numixproject/numix-icon-theme/issues/190, cf. https://github.com/numixproject/numix-icon-theme/issues/190#issuecomment-119197792 and the following conversation.

And who would have thought that `clipit-trayicon` actually is the app icon name? One of the strangest namings ever :)

**Closed** 2015-07-15 15:24 UTC
Labels: bug
