### ISSUE TITLE
Kdeconnect indicator icons

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#1178] opened 2017-01-15 17:18 UTC
Here is the list of the tray icons https://github.com/Bajoja/indicator-kdeconnect/tree/master/data/icons/ubuntu-mono-dark/status/22
- [ ] laptop-{connected,disconnected, trusted}
- [ ] smartphone-{connected,disconnected, trusted}
- [ ] tablet-{connected,disconnected, trusted}

Shouldn't cause any Qt problem as the indicator is using Gtk :+1: 

Original issue https://github.com/numixproject/numix-core/issues/3543

**Comment by wa4557** [comment] 2017-04-16 07:38
Duplicate of #1165

**Closed by wa4557** 2017-04-16 07:38 UTC
Labels: request
