### ISSUE TITLE
Big device icons missing / need work

### ISSUE THREAD

**Issue by sljunkie** [numixproject/numix-icon-theme#764] opened 2015-10-02 01:49 UTC
Device/hardware icons are not properly displayed when the desktop asks for a considerable sized one (48x48 +). Many are missing and/or are available in monochrome only.

Example #1: SD card and hard drive icons on Nautilus
![screenshot from 2015-10-01 22-40-17](https://cloud.githubusercontent.com/assets/7532854/10237859/35820790-688e-11e5-9576-eed10cd3c5b7.png)
![screenshot from 2015-10-01 22-40-43](https://cloud.githubusercontent.com/assets/7532854/10237860/36a5c1e8-688e-11e5-9c76-931803426e0d.png)

Example #2 Big device icons on GNOME's bluetooth dialog
![screenshot from 2015-10-01 22-41-27](https://cloud.githubusercontent.com/assets/7532854/10237883/780de91c-688e-11e5-8613-4c7379748827.png)
![screenshot from 2015-10-01 22-41-42](https://cloud.githubusercontent.com/assets/7532854/10237885/79ed4d9a-688e-11e5-9c94-13a1e6912d3a.png)
![screenshot from 2015-10-01 22-42-05](https://cloud.githubusercontent.com/assets/7532854/10237886/7b808dac-688e-11e5-9007-ba841ecfea49.png)

**Comment by wa4557** [comment] 2015-10-02 11:32
I guess this is a duplicate of #664

**Comment by Foggalong** [comment] 2015-10-02 12:10
Think so yeah :)

**Closed by Foggalong** 2015-10-02 12:10 UTC
Labels: duplicate
