### ISSUE TITLE
Evolution email calendar event icon

### ISSUE THREAD

**Issue by SrAceves** [numixproject/numix-icon-theme#1076] opened 2016-06-01 02:07 UTC
For calendar events, the icon in the message body is HUGE -- very annoying:

![captura de pantalla de 2016-05-30 18-58-11](https://cloud.githubusercontent.com/assets/12215943/15696178/ad2e614a-2773-11e6-8b7d-4b5599f8c0d1.png)

**Comment by palob** [comment] 2016-06-01 23:03
Whoops. What's your Evolution version? Where exactly does it show up and how does it look like with other themes?

**Comment by SrAceves** [comment] 2016-06-01 23:21
Evolution version 3.18.5.2 (in Ubuntu Gnome 16.4). It is the only place that shows up and it looks for the themes in the global locations -- not sure where that is.

**Comment by SrAceves** [comment] 2016-06-01 23:23
It seems that this is the themes directory: `/usr/share/themes`

**Comment by palob** [comment] 2016-06-02 06:34
I meant where do you have to navigate to in order to see it. Can you make a screenshot of how it looks like with another icon theme, e.g. ``Adwaita``?

**Comment by SrAceves** [comment] 2016-06-02 23:57
For some reason, github is not letting me upload the image.

As a description, the adwaita icon looks small enough to fit on a line of text.

**Comment by wa4557** [comment] 2016-07-09 16:11
@SrAceves Are you talking about this huge magenta/orange blobs in your first screenshot? I cannot reporduce that. A screenshot would be great

**Comment by SrAceves** [comment] 2016-07-09 16:36
Nope; it's this icon blown up:

![captura de pantalla de 2016-07-09 11-18-41](https://cloud.githubusercontent.com/assets/12215943/16708901/187287e4-45c7-11e6-8b42-51b89c09cf04.png)

In the actual message, it looks like this (though it doesn't fit in my screen):
![captura de pantalla de 2016-07-09 11-29-56](https://cloud.githubusercontent.com/assets/12215943/16708948/890d84ee-45c8-11e6-8fde-e9caa91ae662.png)

Also this one (a down arrow) which i didn't report inintially:

![captura de pantalla de 2016-07-09 11-34-04](https://cloud.githubusercontent.com/assets/12215943/16708978/186730fe-45c9-11e6-93a3-bf66309cfbe8.png)

The images rescale as you move to a larger screen -- it's just gobbling up screen realestate!

**Comment by wa4557** [comment] 2016-07-10 07:50
oO Can you post the same screenshot with another icon ttheme? I still cannot reproduce that

**Comment by SrAceves** [comment] 2016-07-23 00:13
Here they are (in the same order):

![captura de pantalla de 2016-07-22 19-05-01](https://cloud.githubusercontent.com/assets/12215943/17074344/3aa3bd14-5040-11e6-9d25-cb2ac4ef421f.png)

![captura de pantalla de 2016-07-22 19-06-03](https://cloud.githubusercontent.com/assets/12215943/17074357/42fc742e-5040-11e6-9010-7583d76aa89f.png)

![captura de pantalla de 2016-07-22 19-09-46](https://cloud.githubusercontent.com/assets/12215943/17074362/4d2967c2-5040-11e6-8d30-5e5ac74651f0.png)

**Comment by wa4557** [comment] 2016-09-05 11:04
I guess this has to do ssomething with our `index.theme` file. But no idea what exactly...

**Comment by hlechner** [comment] 2016-12-29 22:29
In the past I found some similar bugs with some different applications, when the application has not fully tested with not-fixed icons, so it scales as far as it have space in the screen, at least seems similar.

@SrAceves have you tried with a different GTK theme? can you test with Adwaita (not the black one)?

**Comment by palob** [comment] 2017-01-05 14:51
Can somebody post a screenshots with other themes? I'd like to know how it's supposed to look and where the huge icons originate from.

**Comment by palob** [comment] 2017-01-05 15:00
Can somebody tell me what I need to do in order to see the oversized icon in Evolution?

**Comment by hlechner** [comment] 2017-01-05 19:40
Maybe it's a evolution bug related to this one fixed in 2015:
https://bugzilla.gnome.org/show_bug.cgi?id=741093

**Comment by manofthepeace** [comment] 2017-01-05 20:56
On a accepted meeting, it looks like to be this
![evo_icon1](https://cloud.githubusercontent.com/assets/13215031/21697085/bdb94aec-d35e-11e6-8bd0-11efc6708451.png)

In the bottom it seems to be the lightbulb;
![evo_icon2](https://cloud.githubusercontent.com/assets/13215031/21697096/c9b3ebf4-d35e-11e6-8943-74ba68c82074.png)

So basically to reproduce; in my theme settings I just set the icons to Numix, then problem appears right away when I open a meeting in Evolution (preview or open) (yeah we switched from TB to evolution...). The icon you highlighted in the screenshot seems ok also, I think this one and the one I copied get replaced by the same one in numix.

**Comment by palob** [comment] 2017-01-05 21:54
@hlechner That sounds suspicious but to me it looks like it was fixed before 3.18.

Two icons in question here are the following:
![stock-icons](https://cloud.githubusercontent.com/assets/7050624/21698703/8c9a4c2e-d398-11e6-939b-6ebd67d3aa8b.png)

In contrast to @SrAceves I can't find them in Evolution 3.22. It just looks like this:
![evolution](https://cloud.githubusercontent.com/assets/7050624/21698795/1ba6ac3c-d399-11e6-99ec-49e7540a614b.png)

I know that in the 3.20 cycle the Evolution contributors beefed up the icons. I can't find any ``stock_new-meeting`` outside of Numix on my machine. Evolution's icons (``/usr/share/evolution/icons...``) now look like this:
![evolution-icons](https://cloud.githubusercontent.com/assets/7050624/21698908/984d40d4-d399-11e6-9bd7-2b45d40be112.png)

So whether it's this or what @hlechner linked to above I'm pretty sure it is an Evolution bug now fixed upstream. I don't know how to fix it anyway, our ``index.theme`` already reads ``Fixed`` for all action icons.

**Comment by manofthepeace** [comment] 2017-01-06 18:19
I tried to update my evolution to 3.20 on 16.04, but it made a big mess, had to revert back. But Found something else though. in The meeting invite the huge icon at the botton is the first button. Basically the icon becomes the button, and it scales;

Adwaita;
![evolution_3](https://cloud.githubusercontent.com/assets/13215031/21728027/1144c156-d412-11e6-915b-0fe7e0ff33ae.png)

Numix;
![evolution_4](https://cloud.githubusercontent.com/assets/13215031/21728072/4788971a-d412-11e6-8926-8d2a1531caef.png)

each time I click somewhere the icon gets bigger

Would there be a way to disable icons in the gtk css EmailDisplay. Or to make those not scalable at all, anywhere? With GtkInspector I could not get the specific icon in the emailDisplay so not sure to to at least workaround the issue. In the screenshot from @palob in the list email view, the icon is there on 3.18, but the size is ok, it's really only in the emailDisplay.

**Comment by bil-elmoussaoui** [comment] 2017-01-06 18:25
@manofthepeace can you try with an other icon theme? i think the issue is related to Evolution as the icon size should be fixed by the application itself and scaled down if the icon size is not correctly detected.

**Comment by manofthepeace** [comment] 2017-01-06 18:33
Other icon theme works, see picture I posted previously with Adwaita. It only happen with numix. But I really like numix ;) So I do not really want to give up on it just because of evolution. So any workaround would make me happy. I tried to to customize the css for that item by myself for evolution, but without success. Not sure also why other icon theme would work also, I mean why would evolution behave correctly with other icon theme.

thanks for your support!

**Comment by manofthepeace** [comment] 2017-01-06 18:44
Quick update. same bug with evolution 3.20

**Comment by palob** [comment] 2017-01-06 18:44
Adwaita is PNG-based while Numix is SVG-based. Can you try with any other SVG theme?

**Comment by manofthepeace** [comment] 2017-01-06 18:47
Just tried with Humanity, which seems to be svg based, and everything is ok

**Comment by bil-elmoussaoui** [comment] 2017-01-06 18:48
It works perfectly here using Evolution 3.22
![capture d ecran de 2017-01-06 19-45-23](https://cloud.githubusercontent.com/assets/7660997/21728868/bd7ae712-d448-11e6-9ec7-0cb11156f6e7.png)
I tried with Paper icon theme, and it works perfectly too! Which version of Numix are you using? the gtk version too?

**Comment by manofthepeace** [comment] 2017-01-06 18:50
You need to have a meeting, and open that meeting, it's 2 icons inside a meeting that are scaled. All the rest in evolution with numix is perfectly fine. I use numix-gtk-theme + numix-icon-theme from the PPA so gtk-theme version 2.6.6+626 ans icon theme 0.3+872

**Comment by palob** [comment] 2017-01-06 18:54
Can't reproduce it either. But I'm still not sure if I'm looking in the right places. I find Evolution's UI massively cluttered.

**Comment by manofthepeace** [comment] 2017-01-06 18:59
Probably you can do it with each other;
1- Send a meeting invite to an other
2- The other person will receive the invite in his "Boite de Réception"
3-In that meeting invite you received; in boite de réception, 2 icons scales super big.

**Comment by bil-elmoussaoui** [comment] 2017-01-06 19:25
@manofthepeace in that case it's an upstream bug that should be reported to Evolution, as they seem to forgot to scale down those icons :+1:

**Comment by manofthepeace** [comment] 2017-01-06 19:29
Hum, would you know why other svg icon themes are working fine though? I am a bit skeptical, sorry for that. Would you think it would fix the bug if I transform the only 2 svg where I have the issue into png?!

**Comment by bil-elmoussaoui** [comment] 2017-01-06 19:37
Can you give a screenshot where it works fine with an other svg theme?

**Comment by manofthepeace** [comment] 2017-01-06 20:12
With Humanity;
![evolution_5](https://cloud.githubusercontent.com/assets/13215031/21731403/36317ef4-d422-11e6-912d-0849306578db.png)

The first button "open calendar" is replaced by the giant blue icon in numix
This screenshots comes from the Boite de réception preview of a meeting I received. If I double click on the received email/meeting from the inbox, it opens the email itself and issue is not present also with Humanity theme, but is with numix. All the rest in evolution is top notch! Only the meeting invites in the email display that the weird behaviour is present.

**Comment by hlechner** [comment] 2017-01-06 20:29
Maybe it's a time to try to replicate the environment into a virtualization.

I confess that I'm not a mail application fan but I can try it, let me check your system:
- Ubuntu 16.04
- Evolution 3.18.5.2 (from repository)
- numix-gtk-theme 2.6.6+626 (PPA)
- numix-icon-theme 0.3+872 (PPA)

@manofthepeace do you believe if I install this system into a virtualbox configuring the evolution for IMAP having a invite to meeting into it I can reproduce this behavior? If there are more variable of this process please let me know.

And I would say **thank you** for not leaving the issue, some people give up on the issues so we can't at least try to solve.

**Comment by hlechner** [comment] 2017-01-06 20:33
If it's not too much and you have a bit of time to try one more thing in your side:

- Virtualize the [Ubuntu 16.10](http://releases.ubuntu.com/16.10/) (you can use virtualbox)
- Test the Evolution

Ubuntu 16.10 have the evolution 3.22 in the repository.

If you can't is ok also.

**Comment by manofthepeace** [comment] 2017-01-06 20:52
I can do it for sure ;)  will not commit to a date though,but will do it soon. There are really no variable. Your bullet list is perfect. One thing I can maybe add, but I doubt it makes a difference. My meetings are from a evolution-ews (exchange/office365). But I am pretty sure if you sync a gmail account, and receive a meeting invite you should be able to reproduce by previewing it from your inbox.

Sorry for not sending complete screenshots, some portion are confidential, I could probably blurry some part and send something more complete. Let me know if it would help

The thanks goes to you guys, you are doing the work, not me.

**Comment by manofthepeace** [comment] 2017-01-06 21:34
I did a vm with 16.10 but I do not seem to be able to add my exchange account. Will take a bit more time. Have a good w-e all.

**Comment by manofthepeace** [comment] 2017-01-06 21:49
Ok I could reproduce in 16.10 with my IMAP account. Exact same behaviour using ubuntu 16.10 + evolution 3.22. I used one of my email, went to agenda created a new meeting to my other imap account. On the second account I got the invite in my inbox, and icon were huge and scaled.

**Comment by hlechner** [comment] 2017-01-06 22:07
I'm still trying to set it up.

It keep refusing my gmail password, and it's already allowed on google configuration.

When I get it working I'll return here.

**Comment by hlechner** [comment] 2017-01-06 23:09
![image](https://cloud.githubusercontent.com/assets/11244067/21735944/69ace746-d454-11e6-8d66-b4c4d6b0dae4.png)

Bingo!

**Comment by hlechner** [comment] 2017-01-07 00:40
![image](https://cloud.githubusercontent.com/assets/11244067/21737326/c9ca2378-d45e-11e6-8468-541ff75d82d4.png)

I've already found what is going on:

Our SVGs uses the following code:
``viewBox="0 0 16 16"``

somehow it is causing this bug in Evolution. If we change the following code to:
``height="16" width="16"``

the problem will be solved.

The following icons get huge on evolution:
- stock_new-meeting.svg (16px)
- go-bottom.svg (?)

**Comment by hlechner** [comment] 2017-01-07 00:43
I believe that it must be reported into the Evolution bug tracker, but we can "solve" it on icons so the users can use the Numix with Evolution until the bug was not fixed upstream.

**Comment by manofthepeace** [comment] 2017-01-07 03:47
Awesome. Just tested it, it works! Indeed it should be fixed by evolution, it's not a "that clean fix". But I am happy with it anyway, I can use numix icon without seeing that weird behaviour in evolution. Thanks you all that participated, you're awesome, great team. I really appreciated your super fast feedback.

**Comment by hlechner** [comment] 2017-01-07 04:07
You're welcome!

By the way, I've raised the issue into the Evolution bug tracker:
https://bugzilla.gnome.org/show_bug.cgi?id=776969

**Comment by palob** [comment] 2017-01-07 14:01
Thanks for your research, @hlechner.

I've just come across an isuue which might or might not be related. For tracks without album assignment in the metadata **Lollypop** shows ``folder-music-symbolic`` as cover art for default. For smaller sizes and SVG themes though the icon seems to be clipped the wrong way (tested with ``Numix``, ``elementary``, ``Papirus``.

Here's a screenshot from ``~/.cache/lollypop/``
![folder-music-symbolic](https://cloud.githubusercontent.com/assets/7050624/21742194/c7f511a8-d4e9-11e6-9f86-ec3ad7140a91.png)

With ``breeze`` however`` everything is rendered correctly. They have got
```SVG
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">
```
as the first line.

**Comment by hlechner** [comment] 2017-01-08 01:45
@palob let me check it if I can find what is happening on this issue specifically.

**Comment by hlechner** [comment] 2017-01-08 02:46
@palob What is going on in this case: lollypop instead of use the full size they just try to adjust the icon just in the middle of the image, which is a lot lower size then we expect. Look this example:
![image](https://cloud.githubusercontent.com/assets/11244067/21746846/8d2e349a-d53a-11e6-82a8-60663f7d2ec3.png)

To lollypop shows the _48 correctly I have changed the ``index.html`` from:
```
[scalable/places]
Size=16
MinSize=16
MaxSize=512
Context=Places
Type=Scalable
```
to:
```
[scalable/places]
Size=16
MinSize=8
MaxSize=512
Context=Places
Type=Scalable
```

It's a strange application behavior, but I think it was developed that way. To change the MinSize to fix just for lollypop it maybe generate strange behavior in different apps.

Lollypop if not allowed to resize the icon for the size needed they will use the MinSize and crop it, that is why you have seen just part of the icon being generated.

**Comment by palob** [comment] 2017-01-08 11:34
Alright, thanks. As far as I can see a lot of other themes have got ``MinSize=8`` for ``Size=16``.
@wa4557 @hlechner Should we change it or do you know of any negative side effects?

**Comment by palob** [comment] 2017-01-08 11:37
@hlechner, regarding the ``viewBox`` to ``height/width`` I think it's safe to do this for the three icons in question, I couldn't think of any downside.

**Comment by wa4557** [comment] 2017-01-08 11:45
@palob Reducing MinSize of smalles icons is definitely no problem, if we don't touch any other sizes.

**Comment by hlechner** [comment] 2017-01-08 16:07
If there is no problem with ``MinSize`` being "8" let's change it then.

Regarding to the``viewBox`` I think we can do it, but you guys use a shell script to reduce the icons size right? This script can't revert this change in the future?

**Comment by hlechner** [comment] 2017-01-08 16:18
Oh, just remembering about ``MinSize`` due to this lollypop issue:

@palob shows the screenshot of the images of 45, 48 and 200. But I found on the same folder the 32 version too.

The ``MinSize`` "8" is not enough to the 32. it needs to be even lower. Numix icon will "suffer" more than Breeze because the icon itself uses all 16px and the breeze one have some "border" pixels invisible/not used.

Even with the solution in our side I believe we should report to them, they can produce the images from different ways. @palob could you report this issue to the developers?

**Comment by hlechner** [comment] 2017-01-09 22:08
Good news guys: Evolution fixed it upstream, reported by them on the issue that I've created.

> Thanks for a bug report.
> 
> (In reply to Henrique Lechner from comment #0)
> > As workaround it's possible to change the SVG by removing the following
> > attribute:
> > viewBox="0 0 16 16"
> > 
> > And adding:
> > height="16" width="16"
> 
> Just to clarify, the above is for the SVG images, which the evolution has out of the control.
> 
> On the evolution side, the icons are drawn using WebKitGTK+, thus they are part of an HTML page. It looks like the viewBox is not the same as specifying width/height for it. I do not blame WebKitGTK+, the Evolution should define width/height of the <img> anyway, which is what I did.
> 
> Created commit 25d8b4e in evo master (3.23.4+)
> Created commit 8a0000f in evo gnome-3-22 (3.22.4+)

Link: https://bugzilla.gnome.org/show_bug.cgi?id=776969

**Comment by bil-elmoussaoui** [comment] 2017-01-09 22:14
@hlechner is having both width/height and viewBox does not break anything? if it's the case we should add  that to all the icons ;) of course we should try that first!

**Comment by hlechner** [comment] 2017-01-09 22:43
This behavior is a specific bug, I don't think we should change all icons for this, maybe we can create different bugs in different applications doing it.

If we found a similar issue in the future we should report upstream and also use width/height just on the affected icons by the application.

**Closed** 2017-01-11 16:59 UTC
Labels: bug
