### ISSUE TITLE
Chrome icon on desktop is small

### ISSUE THREAD

**Issue by xhpohanka** [numixproject/numix-icon-theme#621] opened 2015-07-08 07:49 UTC
![chrome-small](https://cloud.githubusercontent.com/assets/2233252/8565469/6f4dfc0c-2556-11e5-9b73-ee82a28c9dc5.png)

Title and screenshot says everything...
Tested on Archlinux, Cinnamon 2.6

**Comment by wa4557** [comment] 2015-07-08 07:50
Duplicate of #192. I guess this will be resolved pretty soon, we already know how to deal with it

**Closed** 2015-07-08 11:06 UTC
Labels: duplicate
