### ISSUE TITLE
Wrong coloring for devices/nm-device-wired.svg makes nm-applet indicator look out of place

### ISSUE THREAD

**Issue by alxgrtnstrngl** [numixproject/numix-icon-theme#186] opened 2014-10-01 13:00 UTC
The panel applet nm-applet that comes with NetworkManager displays a very odd icon when used with Numix icon theme.  It's a strange color that doesn't fit with the Numix monochrome status indicator icons design pattern.  This is already mentioned in Issue #114 and I think it should be changed.  The icon for devices/nm-device-wired.svg should be made monochrome.

**Comment by bil-elmoussaoui** [comment] 2015-03-28 10:09
This is fixed by now ?

**Comment by dirtydancing** [comment] 2015-03-28 13:09
@bil-elmoussaoui Presently, the `nm-device-wired.svg` icon in `48x48/devices` is still coloured like described above. 

Screenshot of current Numix base:

![nm-device-wired](https://cloud.githubusercontent.com/assets/7164227/6881162/d0ba24f0-d553-11e4-9f0c-5bf4207a6b70.png)

Where is this displayed in your distribution? Could you provide a screenshot, if possible?

**Comment by Foggalong** [comment] 2015-03-28 17:09
@dirtydancing is this a duplicate of #114 ?

**Comment by dirtydancing** [comment] 2015-03-29 14:22
@Foggalong Well, I guess both of these issues started out with the panel status icon, and as such both can now be closed. If an issue should come up with `nm-device-wired.svg` in `48x48/devices`, that would arguably be a new issue and should be opened as a new issue then.

Bottom line: I believe that both this issue and https://github.com/numixproject/numix-icon-theme/issues/114 can be closed now.

**Comment by dirtydancing** [comment] 2015-04-18 09:41
With https://github.com/numixproject/numix-icon-theme/issues/461, this issue can be closed now.

**Comment by dirtydancing** [comment] 2015-05-03 09:00
New icon design has been merged, cf. https://github.com/numixproject/numix-icon-theme/pull/468, so this can be closed now :)

**Closed** 2015-05-03 09:40 UTC
Labels: enhancement
