### ISSUE TITLE
Fix bad nvidia prime-indicator panel icon 

### ISSUE THREAD

**Issue by alkaef** [numixproject/numix-icon-theme#1062] opened 2016-04-17 08:26 UTC
After installing prime-indicator the default icon shown on the panel will be like this:
![screenshot from 2016-04-17 09 03 02](https://cloud.githubusercontent.com/assets/13399275/14584666/bd1fdd92-047b-11e6-8064-5c0d8fac30a2.png)

Notice the numix circle icon is shown instead of the nvidia-panel icon which doesn't fit. 
To fix this copy `nvidia-panel.svg` on `/usr/share/icons/Numix-Light/16/status/` to `/usr/share/icons/Numix-Light/16/panel/`. Do the same on `Numix` icon folder if you are using a dark theme.

**Fixed icon preview**
![screenshot from 2016-04-17 09 06 50](https://cloud.githubusercontent.com/assets/13399275/14584685/3f27a36a-047c-11e6-92ca-1bd880c68878.png)

**Comment by wa4557** [comment] 2016-04-17 08:55
duplicate of #1021. What you did is not really a fix, because if you do that the status icon will show up also in the dash and launcher, right?

**Comment by alkaef** [comment] 2016-04-17 09:58
@wa4557 nah, its a fix for me. I suppose `panel` icons is for status bar, whereas application icons is in `48/apps`
![screenshot from 2016-04-17 16 56 29](https://cloud.githubusercontent.com/assets/13399275/14586281/6962f490-04bd-11e6-8dea-2dc3cccc5c1f.png)

**Comment by palob** [comment] 2016-04-17 14:09
Hmm, there is no icon ``nvidia-panel`` in Circle. So why did ``nvidia`` show up?

The same problem as where ``nemo`` from Circle shows up instead of ``nemo-eject`` from base (which however doesn't seem to be fixable)?

**Comment by alkaef** [comment] 2016-04-18 07:21
@palob you can find the `nvidia-panel` icon in `Numix` and `Numix-Light` inside `16/status`. And yes, there is no `nvidia-panel` icon in `Numix-Circle` or `Numix-Circle-Light`. _Afaik_ the circle theme inherits numix and numix light as their base theme so even there is no nvidia-panel icon inside the circle theme folder, it will be inherited from numix base theme anyway. If there is **no panel icon** for the app in the base theme --or the icon use different name, the circle theme will took it's place.

**Closed** 2016-06-18 19:33 UTC
Labels: bug

**Comment by imkzh** [comment] 2020-07-20 13:47
@palob possible fix for ``nemo-eject`` icon end up with circle version: 

Create a symlink to ``../../Numix/actions`` in ``Numix-Circle/16`` and add the following section to ``/usr/share/icons/Numix-Circle/index.theme``

```
[16/actions]
Size=16
Context=Actions
Type=Fixed
```
and insert ``16/actions,`` right after ``Directories=`` on line 16 would fix the problem.

**Comment by palob** [comment] 2020-07-20 21:04
Thank you, will need to look into this and install Nemo again.
