### ISSUE TITLE
Telegram top panel icon

### ISSUE THREAD

**Issue by orkhanfarmanli** [numixproject/numix-icon-theme#1026] opened 2016-03-22 13:48 UTC
Hello there. 

Firstly I want to mention that I really appreciate your hard work. Thanks for this beautiful icons. I want to inform you about one issue. There is no telegram icon for the top panel in ubuntu. As you can see in the screen (the link below) every other app has the numix icon except telegram. I am keen to see this icon in next update. 

Thanks in advance.

https://cloud.githubusercontent.com/assets/14097805/13953568/fdfa1f74-f055-11e5-8aa7-be2d2de74edf.png

**Comment by Foggalong** [comment] 2016-03-22 16:11
Duplicate of #669

**Closed by Foggalong** 2016-03-22 16:11 UTC
Labels: duplicate
