### ISSUE TITLE
Bug on document-open-symbolic.svg

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme#987] opened 2016-01-03 19:28 UTC
It occur on gnome-tweak software.

Adwaita:
![image](https://cloud.githubusercontent.com/assets/11244067/12080270/b888d6da-b23c-11e5-83bf-d2102828d8dc.png)
![image](https://cloud.githubusercontent.com/assets/11244067/12080309/e2dbd7ce-b23d-11e5-8929-44038e4f0a09.png)
Evopop:
![image](https://cloud.githubusercontent.com/assets/11244067/12080272/d5e04196-b23c-11e5-9fa7-83e22b756090.png)
![image](https://cloud.githubusercontent.com/assets/11244067/12080300/ae508144-b23d-11e5-81fe-b2a4200f299b.png)
Numix:
![image](https://cloud.githubusercontent.com/assets/11244067/12080276/f9d1c912-b23c-11e5-80ac-494aca211419.png)
![image](https://cloud.githubusercontent.com/assets/11244067/12080297/7c5c68ec-b23d-11e5-8cf5-7d109ed9a4f6.png)
Numix-Light:
![image](https://cloud.githubusercontent.com/assets/11244067/12080279/1811db56-b23d-11e5-86d0-2d0f8aeb3d4c.png)
![image](https://cloud.githubusercontent.com/assets/11244067/12080289/4fed62ca-b23d-11e5-9a0e-065c00a83531.png)

It seems that is happening because there are two parts on these icons:
- back (path)
- front (stroke without fill color)

![image](https://cloud.githubusercontent.com/assets/11244067/12080336/b91b8596-b23e-11e5-922d-383a21343eee.png)![image](https://cloud.githubusercontent.com/assets/11244067/12080340/e5b245f4-b23e-11e5-83d0-1bd5b6cf215c.png)

But I need to be honest, even with the intended design it's hard to recognize what is the icon design.

**Comment by wa4557** [comment] 2016-01-04 08:10
Yeah that was one of the worse. I'll think of something closer to the fixed sizes after the maintenance PRs have been merged

**Comment by dirtydancing** [comment] 2016-01-04 10:10
I can confirm this issue with Arch/GNOME, and yes, this is due to a stroke being used in the .svg file:

![stroke](https://cloud.githubusercontent.com/assets/7164227/12087453/4d2846ae-b2d3-11e5-8235-0c1f31505b45.png)

@wa4557 Great, thanks!

**Closed** 2016-01-19 22:42 UTC
Labels: bug
