### ISSUE TITLE
Please do regular releases

### ISSUE THREAD

**Issue by jbicha** [numixproject/numix-icon-theme#1089] opened 2016-06-17 00:16 UTC
It would be a help to distros if you made regular releases.

Debian policy encourages providing an easy way for anyone to re-download the original source straight from the debian packaging. It's quite a bit easier for the Debian maintainer to do that when there are tarballs or at least git tags.
> get-orig-source (optional)
> This target fetches the most recent version of the original source package from a canonical archive site (via FTP or WWW, for example), does any necessary rearrangement to turn it into the original source tar file format described below, and leaves it in the current directory.
> This target is optional, but providing it if possible is a good idea.
> -- https://www.debian.org/doc/debian-policy/ch-source.html#s-debianrules

**Comment by jbicha** [comment] 2016-06-17 00:17
I guess this is a duplicate of issue #1056

**Comment by Foggalong** [comment] 2016-06-18 19:36
Even earlier, a duplicate of #855

**Closed by Foggalong** 2016-06-18 19:36 UTC
Labels: duplicate
