### ISSUE TITLE
Big charging battery icon - Unity

### ISSUE THREAD

**Issue by proudh0n** [numixproject/numix-icon-theme#1047] opened 2016-04-03 08:41 UTC
All the charging battery icons are bigger than the normal ones, this wasn't happening a week ago, so must be something from one of the latest updates. I have this issue on Ubuntu 14.04 LTS with Unity desktop.

![screenshot](https://cloud.githubusercontent.com/assets/8055505/14231562/7f7bb9d2-f988-11e5-9c42-292b02b8ca7a.png)

**Comment by dirtydancing** [comment] 2016-04-03 15:29
This is strange, because the power indicator for Ubuntu 14.04 LTS, http://packages.ubuntu.com/de/trusty/indicator-power, appears not to have changed recently.

Cf. also the code screenshot over at https://github.com/numixproject/numix-icon-theme/issues/107#issuecomment-52552715 and the battery icon name overview at https://github.com/numixproject/numix-icon-theme/issues/107#issuecomment-98399311.

@proudh0n Is this only related to the charging icons (and not to full charged and/or discharging)?

**Comment by wa4557** [comment] 2016-04-03 18:26
I cannot reproduce this in 15.10. For me the charging icon has the exact same size as the other ones....

**Comment by proudh0n** [comment] 2016-04-05 07:34
@dirtydancing It seems only to happen on charging icons. On discharging doesn't happen, but on fully charged I'm not sure. I'll check it and post feedback.

As I said, this started about a week ago, maybe is something related to my computer...

**Comment by dirtydancing** [comment] 2016-04-05 08:22
@proudh0n Is this the regular Ubuntu 14.04 LTS, given that your screenfetch displays kernel version 4.5.0? In comparison: regular Arch is currently running with kernel version 4.4.5.

Also, just in case, could you check if changing the GTK theme makes any difference? (it should not, but experience shows that sometimes battery icon size issues are somewhat exotic)

Finally, is the battery icon size fine in the dropdown menu that shows in Ubuntu when the battery icon is clicked, or is the same battery icon size issue present there as well?

**Comment by dirtydancing** [comment] 2016-04-05 08:24
@proudh0n Is this the regular Ubuntu 14.04 LTS, given that your screenfetch displays kernel version 4.5.0? In comparison: regular Arch is currently running with kernel version 4.4.5.

Also, just in case, could you check if changing the GTK theme makes any difference? (it should not, but experience shows that sometimes battery icon size issues are somewhat exotic)

Finally, is the battery icon size fine in the dropdown menu that shows in Ubuntu when the battery icon is clicked, or is the same battery icon size issue present there as well?

**Comment by proudh0n** [comment] 2016-04-05 11:46
@dirtydancing  It's regular Ubuntu 14.04 LTS but with newer kernel, but right now I'm using the regular kernel and the issue is there.

I've tried with regular ubuntu icon theme and it seems to fit, but as is on landscape it's difficult to say that it's size is regular or big. With default humanity icon theme it also seems bigger than usual, like with Numix

This is the screenshot:

![captura de pantalla de 2016-04-05 13 39 41](https://cloud.githubusercontent.com/assets/8055505/14280610/1c6346a0-fb34-11e5-8b40-81c7f7819caf.png)

On the dropdown it also seems to be bigger than usual. I see it bigger than the wireless mouse for example.

Screenshot:

![area de trabajo 1_003](https://cloud.githubusercontent.com/assets/8055505/14280701/a5ce5556-fb34-11e5-9da7-2ef2f90e26d1.png)

**Comment by dirtydancing** [comment] 2016-04-05 16:06
Well, unfortunately I have to say that I am not sure what is going on there with Ubuntu 14.04 LTS, given that all was fine until recently, and also given that this is not reproducible with Ubuntu 15.10, cf. above.

Maybe for some reason, Ubuntu 14.04 LTS is now using "symbolic"-named icons (16x16) from the `scalable` directory for charging, and these get scaled up to 22x22 in the top bar. So what you could try is delete the `battery` icons in `scalable/status` and see if all is fine then.

Oh, and with Ubuntu, display scaling might cause problems as well, although that should relate to all battery status icons, not just to charging. Possibly, also this comment might be of help: https://github.com/numixproject/numix-icon-theme/issues/107#issuecomment-65576033.

**Comment by proudh0n** [comment] 2016-04-05 17:13
@dirtydancing  I've tried to delete the battery-* icons from scalable/status (I moved them to another dir) and unfortunately now the charging icons are totally missing. What is strange is that the discharging ones still showing fine :/

Screenshot (charging):
![captura de pantalla de 2016-04-05 19 11 56](https://cloud.githubusercontent.com/assets/8055505/14291127/4aafc622-fb62-11e5-92e2-d6e44126bebe.png)

Screenshot (discharging):

![captura de pantalla de 2016-04-05 19 12 34](https://cloud.githubusercontent.com/assets/8055505/14291143/6338a218-fb62-11e5-9ec2-64220c38bbf8.png)

I don't understand what happens, but if I'm the only one it may be something related to my installation. Many thanks for your help :)

**Comment by dirtydancing** [comment] 2016-04-05 18:46
You are welcome, yes, this is hard to understand :), and yes, this might be related to your installation.

Anyways, one more thing you might try after removing the battery icons in `scalable/status` is a forced icon cache update: `sudo gtk-update-icon-cache -f /usr/share/icons/Numix` Good luck!

**Comment by proudh0n** [comment] 2016-04-05 18:55
@dirtydancing  Indeed, updating the icon cache fixed the size issue, but right now at 94% battery, if I plug the charger it displays the icon as fully charged. I don't really know if that's how is supposed to be, I'll check later when the battery capacity is lower. Thanks for all our help!

**Comment by dirtydancing** [comment] 2016-04-05 19:29
:+1: 

As to the battery icon displayed: Different DE/distributions and also e.g. different versions of Ubuntu handle this individually. You might simply check along the way. This code screenshot might be of help for the battery icon thresholds of Ubuntu 14.04 LTS: https://github.com/numixproject/numix-icon-theme/issues/107#issuecomment-52552715

**Comment by proudh0n** [comment] 2016-04-05 19:49
@dirtydancing  I just plugged the charger for a moment only to see if the issue is fixed, and indeed, all working fine. I don't know thy this issue started and I don't know if on the next update it will happen again. Hope it doesn't, but at least I know how to fix it.

Appreciate all your help :)
![captura de pantalla de 2016-04-05 21 47 51](https://cloud.githubusercontent.com/assets/8055505/14295978/3e6753a6-fb78-11e5-8213-b173c39de708.png)

**Comment by dirtydancing** [comment] 2016-04-05 20:14
iirc, in Ubuntu 14.04 LTS the difference between the charging and the discharging battery icons is caused by Ubuntu using primarily "symbolic"-named battery icons for charging (full, good, low..., less granulated) and "percentage"-named battery icons for discharging (100, 80, 60, 40..., more granulated). This means that there are different battery icons thresholds for charging and for discharging, which might cause confusion.

Later Ubuntu versions are more consistent with the battery icon names for charging and discharging (primarily "percentage"-named for all). In contrast, e.g. GNOME only consistently uses the "symbolic"-named battery icons and thus e.g. Arch/GNOME is less granulated than current Ubuntu/Unity.

**Comment by proudh0n** [comment] 2016-04-05 22:44
@dirtydancing And there is something that can be done from your side? And why it has been ok since now? I'm pretty sure a week ago it was perfectly fine. Thanks for pointing me the difference between tose icons.

**Comment by dirtydancing** [comment] 2016-04-06 07:09
I am not sure what you mean with "something that can be done from your side". There is an encompassing set of battery icons and icon names from Numix's side, established to cater to all DE/distributions, cf. https://github.com/numixproject/numix-icon-theme/issues/107#issuecomment-98399311. The battery icons are a somewhat complex issue, as you can see with https://github.com/numixproject/numix-icon-theme/issues/107. As I am not running Ubuntu 14.04 LTS, I cannot tell what exactly happened at your end.

**Comment by wa4557** [comment] 2016-07-09 16:14
@proudh0n I had the same issue once, and it was related to the display scaling. As soon as you use a value that is not "1" Ubuntu starts using `scalable` icons. Nothing that can be fixed from Numix side I'm afraid

**Comment by Foggalong** [comment] 2016-08-04 18:33
Marking this as an invalid - an issue with the battery indicator. Feel free to update us if anything changes :)

**Closed by Foggalong** 2016-08-04 18:33 UTC
Labels: bug
