### ISSUE TITLE
Missing document-edit-symbolic icon.

### ISSUE THREAD

**Issue by darkshram** [numixproject/numix-icon-theme#1378] opened 2020-09-08 14:52 UTC
Thunar uses a symbolic icon to edit the path bar.

The code in thunar indicates:
`thunar/thunar-location-buttons.c:  icon = gtk_image_new_from_icon_name ("document-edit-symbolic", GTK_ICON_SIZE_BUTTON);`

So, this is the missing icon:
actions/document-edit-symbolic.svg

Numix also lacks the following:
apps/accessories-text-editor-symbolic.svg
apps/text-editor-symbolic.svg

This is how it looks with Numix:
![Captura de pantalla_2020-09-08_09-34-40](https://user-images.githubusercontent.com/10327500/92491323-b79c3b80-f1b7-11ea-8ce5-c568b3f8c949.png)

This is how it looks with Adwaita
![Captura de pantalla_2020-09-08_09-35-05](https://user-images.githubusercontent.com/10327500/92491353-bff47680-f1b7-11ea-83c3-8f50cc88d8ac.png)

The Adwaita icon is:
![Captura de pantalla_2020-09-08_09-36-07](https://user-images.githubusercontent.com/10327500/92491464-e31f2600-f1b7-11ea-98a7-8421e45c4e14.png)

**Comment by palob** [comment] 2020-09-08 15:19
Another one where the theme fails to pick up a fallback. @Foggalong Could something like this be fixed by Inherits?

**Comment by darkshram** [comment] 2020-09-08 16:52
@palob I have tested with 'Inherits' in index.theme and issue is _partially_ fixed. But it looks (weird) like this:
![Captura de pantalla_2020-09-08_11-47-46](https://user-images.githubusercontent.com/10327500/92505174-52514600-f1c9-11ea-957a-f24203cb88f8.png)

With Adwaita icon theme alone:
![Captura de pantalla_2020-09-08_09-35-05](https://user-images.githubusercontent.com/10327500/92505320-8593d500-f1c9-11ea-87c1-f9b6ff3e643d.png)

**Comment by Foggalong** [comment] 2020-09-08 17:44
This issue is bizarre from top to bottom not just because of that weird inherits glitch (which I have _no_ idea about) but also because I use Thunar and I haven't experienced this problem. What version and OS are you using, will try and reproduce?

**Comment by darkshram** [comment] 2020-09-08 21:04
@Foggalong I use a custom distro based on Fedora.

I have found out why the icon looks weird. I just updated adwaita-icon-theem from 3.28.0 to 3.34.3 to get a couple of icons for other things. It packs /usr/share/icons/Adwaita/scalable/actions/document-edit-symbolic.svg, which is the icon used by Thunar. It looks like this (the _weird_ version):
![Captura de pantalla_2020-09-08_15-49-39](https://user-images.githubusercontent.com/10327500/92526391-08795780-f1eb-11ea-8523-aa83ac7704e1.png)

If I downgrade Adwaita icon theme to 3.28.0, then the icon is this one (the pretty one):
![Captura de pantalla_2020-09-08_15-53-07](https://user-images.githubusercontent.com/10327500/92526654-7a51a100-f1eb-11ea-9b19-69b40ba1b288.png)

**Short story:** Inherits works Ok, but it's not a reliable way to fix the issue because the 3rd party changes made to some icons designs. Would be better to create a symbolic link to a Numix icon:

**scalable/actions/edit-symbolic.svg ---> scalable/actions/document-edit-symbolic.svg**

This is the Numix icon:
![Captura de pantalla_2020-09-08_16-00-24](https://user-images.githubusercontent.com/10327500/92527615-e4b71100-f1ec-11ea-95ca-113e4d9c7d94.png)

**Comment by darkshram** [comment] 2020-09-08 21:34
Using Adwaita icon theme 3.32.0 in Inherits, Thunar looks like this:
![Captura de pantalla_2020-09-08_16-27-55](https://user-images.githubusercontent.com/10327500/92529837-dc60d500-f1f0-11ea-89f5-939fed7c3051.png)

Creating a symbolic link from scalable/actions/edit-symbolic.svg to scalable/actions/document-edit-symbolic.svg fixes the issue and looks like this:
![Captura de pantalla_2020-09-08_16-31-38](https://user-images.githubusercontent.com/10327500/92529889-f4385900-f1f0-11ea-85e5-3381ee7e0e71.png)

**Comment by palob** [comment] 2020-09-09 08:06
Thanks for your reasearch, so all we need to fix this is the symlink.

**Comment by darkshram** [comment] 2020-09-09 12:54
This other two symlinks are missing too. Should point to 'edit-symbolic' too.

apps/accessories-text-editor-symbolic.svg
apps/text-editor-symbolic.svg

**Comment by palob** [comment] 2020-09-09 16:47
We don't ship symbolic app icons.
Where are those needed?

**Closed** 2020-09-16 00:34 UTC
Labels: enhancement
